name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 24f2005095@ds.study.iitm.ac.in
        run: echo "Hello, world!"
